### ISSUE TITLE
`lint` command ignores child projects' .eslintrc

### ISSUE THREAD

**Issue by yjcxy12** [sky-uk/blackjack-toolbelt#36]
At the moment, `lint` command uses `.eslintrc` in `toolbelt` project and ignores any `.eslintrc` in child projects. Which means we cannot have some extra rules or modifications in child projects (e.g. in blackjack-accordion#v1 it uses 4 space indentation instead of 2) .

Not sure if this is intended to have same coding styles across every projects. Or should we merge `.eslintrc` in child projects.

**Comment by thomaslloyd** [comment]
I think the intention is to keep the same styles across all projects. I've had to change the indenting on a project I'm working on to satisfy the toolbelt linting. It's a pain to do but worth it in the long run.

**Comment by yjcxy12** [comment]
Another tricky problem is if we are not going to have `.eslintrc` files in child projects, `Sublime Linter` would not work for Sublime Text (not sure about other editors or IDEs).

**Comment by joshnesbitt** [comment]
> Not sure if this is intended to have same coding styles across every projects.

As @thomaslloyd said this is intentional. After discussions with @mackstar we want to enforce all projects to confirm to the same linting for consistency. Any additions to the lint config in toolbelt are welcome, but we want to enforce a single standard rather than per team configs.

I'm not familiar with the ST package, but I'm sure there could be a workaround for this, maybe by specifying which lint command it runs (get it to use `blackjack lint`)?

**Comment by thomaslloyd** [comment]
For Intellij, you can point it to the location of an .eslintrc file to use. Is that not possible in Sublime Linter?

**Comment by yjcxy12** [comment]
Got it. Closing the issue.

**Comment by joshnesbitt** [comment]
Thanks @yjcxy12
